[2023-01-19T05:42:54.444+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ETL_tablas.Closed_deal scheduled__2023-01-19T00:00:00+00:00 [queued]>
[2023-01-19T05:42:54.465+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ETL_tablas.Closed_deal scheduled__2023-01-19T00:00:00+00:00 [queued]>
[2023-01-19T05:42:54.466+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-19T05:42:54.468+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-19T05:42:54.469+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-19T05:42:54.530+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): Closed_deal> on 2023-01-19 00:00:00+00:00
[2023-01-19T05:42:54.536+0000] {standard_task_runner.py:55} INFO - Started process 1405 to run task
[2023-01-19T05:42:54.541+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ETL_tablas', 'Closed_deal', 'scheduled__2023-01-19T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/ETL_automatizado.py', '--cfg-path', '/tmp/tmpit79x_na']
[2023-01-19T05:42:54.544+0000] {standard_task_runner.py:83} INFO - Job 16: Subtask Closed_deal
[2023-01-19T05:42:54.661+0000] {task_command.py:389} INFO - Running <TaskInstance: ETL_tablas.Closed_deal scheduled__2023-01-19T00:00:00+00:00 [running]> on host c178727935f9
[2023-01-19T05:42:54.745+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_tablas
AIRFLOW_CTX_TASK_ID=Closed_deal
AIRFLOW_CTX_EXECUTION_DATE=2023-01-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-19T00:00:00+00:00
[2023-01-19T05:42:54.749+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL_automatizado.py", line 18, in Closed_deals
    engine = create_engine(cadena_conexion)
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line [2023-01-19T05:42:54.444+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ETL_tablas.Closed_deal scheduled__2023-01-19T00:00:00+00:00 [queued]>
[2023-01-19T05:42:54.465+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ETL_tablas.Closed_deal scheduled__2023-01-19T00:00:00+00:00 [queued]>
[2023-01-19T05:42:54.466+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-19T05:42:54.468+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-19T05:42:54.469+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-19T05:42:54.530+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): Closed_deal> on 2023-01-19 00:00:00+00:00
[2023-01-19T05:42:54.536+0000] {standard_task_runner.py:55} INFO - Started process 1405 to run task
[2023-01-19T05:42:54.541+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ETL_tablas', 'Closed_deal', 'scheduled__2023-01-19T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/ETL_automatizado.py', '--cfg-path', '/tmp/tmpit79x_na']
[2023-01-19T05:42:54.544+0000] {standard_task_runner.py:83} INFO - Job 16: Subtask Closed_deal
[2023-01-19T05:42:54.661+0000] {task_command.py:389} INFO - Running <TaskInstance: ETL_tablas.Closed_deal scheduled__2023-01-19T00:00:00+00:00 [running]> on host c178727935f9
[2023-01-19T05:42:54.745+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_tablas
AIRFLOW_CTX_TASK_ID=Closed_deal
AIRFLOW_CTX_EXECUTION_DATE=2023-01-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-19T00:00:00+00:00
[2023-01-19T05:42:54.749+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL_automatizado.py", line 18, in Closed_deals
    engine = create_engine(cadena_conexion)
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 548, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/pymysql.py", line 68, in dbapi
    return __import__("pymysql")
ModuleNotFoundError: No module named 'pymysql'
[2023-01-19T05:42:54.764+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=ETL_tablas, task_id=Closed_deal, execution_date=20230119T000000, start_date=20230119T054254, end_date=20230119T054254
[2023-01-19T05:42:54.785+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 16 for task Closed_deal (No module named 'pymysql'; 1405)
[2023-01-19T05:42:54.797+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-19T05:42:54.830+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
